import { useEffect, useMemo, useRef, useState } from 'react';
import type Konva from 'konva';
import { Arrow, Circle, Ellipse, Group, Layer, Line, Rect, Stage, Text, Transformer } from 'react-konva';
import type { BoardCommand, BoardObject, Participant, RoomSnapshot, Tool } from '../shared/types';

type Viewport={x:number;y:number;scale:number};
const palette=['#3974e8','#e85c62','#24a47a','#9a62db','#f1a737'];
const tools:{id:Tool;icon:string;label:string;key?:string}[]=[{id:'select',icon:'↖',label:'Select',key:'V'},{id:'hand',icon:'✋',label:'Pan',key:'H'},{id:'pencil',icon:'✎',label:'Pencil',key:'P'},{id:'highlighter',icon:'▰',label:'Highlighter'},{id:'eraser',icon:'⌫',label:'Eraser',key:'E'},{id:'text',icon:'T',label:'Text',key:'T'},{id:'rectangle',icon:'□',label:'Rectangle',key:'R'},{id:'ellipse',icon:'○',label:'Ellipse',key:'O'},{id:'line',icon:'╱',label:'Line',key:'L'},{id:'arrow',icon:'→',label:'Arrow',key:'A'}];
const uuid=()=>crypto.randomUUID();
const base=(type:BoardObject['type'],x:number,y:number,creator:string,z:number)=>({id:uuid(),type,x,y,rotation:0,scaleX:1,scaleY:1,z,locked:false,creator,revision:0});
const deckCodes=()=>['A','2','3','4','5','6','7','8','9','10','J','Q','K'].flatMap(r=>[0,1,2,3].map(s=>`${r}${s}`));

export function Board({snapshot,me,emit,sendCursor,react,control,onError}:{snapshot:RoomSnapshot;me:Participant;emit:(c:BoardCommand)=>void;sendCursor:(p:{x:number;y:number},s:string[])=>void;react:(e:string)=>void;control:(a:'lock'|'unlock'|'reset-view')=>void;onError:(e:string)=>void}){
  const [tool,setTool]=useState<Tool>('select');const [color,setColor]=useState(palette[0]);const [selected,setSelected]=useState<string[]>([]);const [drawer,setDrawer]=useState(true);const [viewport,setViewport]=useState<Viewport>({x:0,y:0,scale:1});const [draft,setDraft]=useState<BoardObject>();const [isPanning,setPanning]=useState(false);const [reactionMenu,setReactionMenu]=useState(false);const stageRef=useRef<Konva.Stage>(null);const trRef=useRef<Konva.Transformer>(null);const start=useRef({x:0,y:0});const pinch=useRef<{dist:number;center:{x:number;y:number}}|undefined>(undefined);const lastStrokeSend=useRef(0);const clipboard=useRef<BoardObject[]>([]);
  const canEdit=!snapshot.locked||me.isTutor; const selectedObjects=snapshot.objects.filter(o=>selected.includes(o.id));
  useEffect(()=>{const nodes=selected.map(id=>stageRef.current?.findOne(`#${id}`)).filter(Boolean) as Konva.Node[];trRef.current?.nodes(nodes);trRef.current?.getLayer()?.batchDraw();},[selected,snapshot.objects]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea'))return;const mod=e.ctrlKey||e.metaKey;const match=!mod&&tools.find(t=>t.key?.toLowerCase()===e.key.toLowerCase());if(match)setTool(match.id);if((e.key==='Delete'||e.key==='Backspace')&&selected.length)emit({type:'delete',ids:selected});if(mod&&e.key==='z')emit({type:e.shiftKey?'redo':'undo'});if(mod&&e.key==='d'){e.preventDefault();duplicate();}if(mod&&e.key==='c'){e.preventDefault();clipboard.current=structuredClone(selectedObjects);}if(mod&&e.key==='v'&&clipboard.current.length){e.preventDefault();clipboard.current.forEach(o=>createObject({...structuredClone(o),id:uuid(),x:o.x+28,y:o.y+28,creator:me.id,revision:0,z:snapshot.objects.length}));}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  useEffect(()=>{const reset=()=>fitContent(); window.addEventListener('manipad-reset-view',reset);return()=>window.removeEventListener('manipad-reset-view',reset);},[snapshot.objects]);
  const point=()=>{const p=stageRef.current?.getPointerPosition()||{x:0,y:0};return{x:(p.x-viewport.x)/viewport.scale,y:(p.y-viewport.y)/viewport.scale};};
  function createObject(object:BoardObject){if(!canEdit){onError('The tutor locked the board');return;}emit({type:'create',object});}
  function center(){return{x:(innerWidth/2-viewport.x)/viewport.scale,y:(innerHeight/2-viewport.y)/viewport.scale};}
  function add(kind:string){const c=center(),z=snapshot.objects.length,b=base(kind==='label'?'text':kind as BoardObject['type'],c.x,c.y,me.id,z);let o:BoardObject;
    if(kind==='counter')o={...b,type:'counter',color,size:54}; else if(kind==='numberTile')o={...b,type:'numberTile',value:5,color}; else if(kind==='fractionBar')o={...b,type:'fractionBar',parts:4,shaded:3,color,width:220,height:52}; else if(kind==='deck'){const cards=deckCodes();o={...b,type:'deck',cards,initialCards:[...cards]};} else if(kind==='die')o={...b,type:'die',value:4,color,rollNonce:0}; else if(kind==='pawn')o={...b,type:'pawn',color,label:'A'}; else o={...b,type:'text',text:'Double-tap to edit',color:'#202938',fontSize:24,width:220};createObject(o);}
  function down(e:any){if(e.evt.touches?.length===2){const[a,b]=e.evt.touches;pinch.current={dist:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),center:{x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2}};return;}if(e.target!==e.target.getStage())return;const p=point();start.current=p;if(tool==='select'){setSelected([]);return;}if(tool==='hand'){setPanning(true);return;}if(!canEdit)return;if(tool==='text'){const text=prompt('Add text');if(text)createObject({...base('text',p.x,p.y,me.id,snapshot.objects.length),type:'text',text,color:'#202938',fontSize:26,width:260});return;}if(tool==='pencil'||tool==='highlighter'){const stroke={...base('stroke',0,0,me.id,snapshot.objects.length),type:'stroke' as const,points:[p.x,p.y],color:tool==='highlighter'?'#f6cf45':color,width:tool==='highlighter'?18:4,opacity:tool==='highlighter' ? .32 : 1};setDraft(stroke);createObject(stroke);return;}if(['rectangle','ellipse','line','arrow'].includes(tool)){setDraft({...base('shape',p.x,p.y,me.id,snapshot.objects.length),type:'shape',shapeType:tool as any,width:1,height:1,fill:tool==='rectangle'||tool==='ellipse'?'#ffffff':'transparent',stroke:color,strokeWidth:3});}}
  function move(e:any){if(e.evt.touches?.length===2&&pinch.current){e.evt.preventDefault();const[a,b]=e.evt.touches;const dist=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),centerNow={x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2};const old=viewport.scale,newScale=Math.max(.2,Math.min(3,old*(dist/pinch.current.dist)));const world={x:(pinch.current.center.x-viewport.x)/old,y:(pinch.current.center.y-viewport.y)/old};setViewport({scale:newScale,x:centerNow.x-world.x*newScale,y:centerNow.y-world.y*newScale});pinch.current={dist,center:centerNow};return;}const p=point();sendCursor(p,selected);if(isPanning){setViewport(v=>({...v,x:v.x+(e.evt.movementX||0),y:v.y+(e.evt.movementY||0)}));return;}if(!draft)return;if(draft.type==='stroke'){const next={...draft,points:[...draft.points,p.x,p.y]};setDraft(next);if(Date.now()-lastStrokeSend.current>40){emit({type:'update',ids:[draft.id],patch:{points:next.points} as Partial<BoardObject>});lastStrokeSend.current=Date.now();}}else if(draft.type==='shape')setDraft({...draft,width:p.x-start.current.x,height:p.y-start.current.y});}
  function up(){pinch.current=undefined;setPanning(false);if(draft){if(draft.type==='stroke')emit({type:'update',ids:[draft.id],patch:{points:draft.points} as Partial<BoardObject>});else createObject(draft);setDraft(undefined);}}
  function wheel(e:any){e.evt.preventDefault();const stage=stageRef.current,p=stage?.getPointerPosition();if(!p)return;const old=viewport.scale,scaleBy=1.08,next=e.evt.deltaY>0?old/scaleBy:old*scaleBy,newScale=Math.max(.2,Math.min(3,next));const world={x:(p.x-viewport.x)/old,y:(p.y-viewport.y)/old};setViewport({scale:newScale,x:p.x-world.x*newScale,y:p.y-world.y*newScale});}
  function fitContent(){if(!snapshot.objects.length){setViewport({x:0,y:0,scale:1});return;}const xs=snapshot.objects.map(o=>o.x),ys=snapshot.objects.map(o=>o.y);const minX=Math.min(...xs)-120,maxX=Math.max(...xs)+220,minY=Math.min(...ys)-120,maxY=Math.max(...ys)+180;const s=Math.min(1,(innerWidth-220)/(maxX-minX),(innerHeight-180)/(maxY-minY));setViewport({scale:s,x:(innerWidth-(minX+maxX)*s)/2,y:(innerHeight-(minY+maxY)*s)/2});}
  function duplicate(){selectedObjects.forEach(o=>createObject({...structuredClone(o),id:uuid(),x:o.x+24,y:o.y+24,creator:me.id,revision:0,z:snapshot.objects.length}));}
  function selectObject(id:string,e:any){if(tool==='eraser'){emit({type:'delete',ids:[id]});return;}if(tool!=='select')return;setSelected(s=>e.evt.shiftKey?(s.includes(id)?s.filter(x=>x!==id):[...s,id]):[id]);}
  function updateObject(o:BoardObject,patch:Partial<BoardObject>){if(o.type==='card'&&typeof patch.x==='number'&&typeof patch.y==='number'){const target=snapshot.objects.find(x=>x.type==='card'&&x.id!==o.id&&Math.hypot(x.x-patch.x!,x.y-patch.y!)<44);if(target?.type==='card'){emit({type:'update',ids:[o.id],patch:{...patch,x:target.x+4,y:target.y+4,stackId:target.stackId||target.id,stackOrder:(target.stackOrder||0)+1} as Partial<BoardObject>});return;}}emit({type:'update',ids:[o.id],patch});}
  return <div className={`board ${isPanning?'panning':''}`}>
    <div className="tool-rail" role="toolbar" aria-label="Board tools">{tools.map(t=><button key={t.id} className={tool===t.id?'active':''} onClick={()=>setTool(t.id)} title={`${t.label}${t.key?` (${t.key})`:''}`} aria-label={t.label}><span>{t.icon}</span></button>)}<hr/><label className="color-button" title="Tool color" style={{background:color}}><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label></div>
    <Stage ref={stageRef} width={innerWidth} height={innerHeight-64} x={viewport.x} y={viewport.y} scaleX={viewport.scale} scaleY={viewport.scale} onMouseDown={down} onTouchStart={down} onMouseMove={move} onTouchMove={move} onMouseUp={up} onTouchEnd={up} onWheel={wheel}>
      <Layer>{[...snapshot.objects].sort((a,b)=>a.z-b.z).map(o=><ObjectNode key={o.id} object={o} selected={selected.includes(o.id)} canEdit={canEdit} onSelect={e=>selectObject(o.id,e)} onUpdate={patch=>updateObject(o,patch)} onAction={type=>emit({type,id:o.id} as BoardCommand)}/>) }{draft&&!snapshot.objects.some(o=>o.id===draft.id)&&<ObjectNode object={draft} selected={false} canEdit={false} onSelect={()=>{}} onUpdate={()=>{}} onAction={()=>{}}/>}<Transformer ref={trRef} rotateEnabled enabledAnchors={selectedObjects.some(o=>o.type==='stroke')?[]:['top-left','top-right','bottom-left','bottom-right']} boundBoxFunc={(oldBox,newBox)=>Math.abs(newBox.width)<16||Math.abs(newBox.height)<16?oldBox:newBox}/>{snapshot.participants.filter(p=>p.id!==me.id&&p.cursor).map(p=><Group key={p.id} x={p.cursor!.x} y={p.cursor!.y} listening={false}><Line points={[0,0,0,18,5,13,10,22,14,20,9,11,17,11]} closed fill={p.color} stroke="white" strokeWidth={2}/><Rect x={14} y={20} width={Math.max(46,p.name.length*8+14)} height={24} cornerRadius={7} fill={p.color}/><Text x={21} y={26} text={p.name} fill="white" fontSize={12} fontStyle="bold"/></Group>)}</Layer>
    </Stage>
    <div className="history-controls"><button onClick={()=>emit({type:'undo'})} title="Undo">↶</button><button onClick={()=>emit({type:'redo'})} title="Redo">↷</button></div>
    <div className="zoom-controls"><button onClick={()=>setViewport(v=>({...v,scale:Math.max(.2,v.scale-.1)}))}>−</button><span>{Math.round(viewport.scale*100)}%</span><button onClick={()=>setViewport(v=>({...v,scale:Math.min(3,v.scale+.1)}))}>+</button><button onClick={fitContent} title="Fit content">⌗</button></div>
    <div className="minimap"><div className="mini-grid">{snapshot.objects.slice(0,40).map(o=><i key={o.id} style={{left:`${50+Math.max(-45,Math.min(45,o.x/30))}%`,top:`${50+Math.max(-40,Math.min(40,o.y/20))}%`}}/>)}</div></div>
    {selected.length>0&&<div className="selection-bar"><span>{selected.length} selected</span><button onClick={duplicate}>Duplicate</button><button onClick={()=>emit({type:'reorder',ids:selected,direction:'front'})}>To front</button>{selectedObjects.length===1&&selectedObjects[0].type==='card'&&<button onClick={()=>emit({type:'flipCard',id:selected[0]})}>Flip</button>}{selectedObjects.length===1&&selectedObjects[0].type==='die'&&<button onClick={()=>emit({type:'rollDie',id:selected[0]})}>Roll</button>}{selectedObjects.length===1&&selectedObjects[0].type==='deck'&&<><button onClick={()=>emit({type:'drawCard',id:selected[0]})}>Draw</button><button onClick={()=>emit({type:'shuffleDeck',id:selected[0]})}>Shuffle</button><button onClick={()=>emit({type:'resetDeck',id:selected[0]})}>Reset</button></>}<button className="danger" onClick={()=>{emit({type:'delete',ids:selected});setSelected([])}}>Delete</button></div>}
    <aside className={`library ${drawer?'open':''}`}><button className="library-tab" onClick={()=>setDrawer(!drawer)}><span>✦</span><b>Things</b><i>{drawer?'›':'‹'}</i></button><div className="library-body"><h2>Things to move</h2><p>Tap to add it to the middle.</p><h3>MATH</h3><div className="thing-grid"><Thing icon={<span className="counter-icon"/>} label="Counter" onClick={()=>add('counter')}/><Thing icon={<span className="tile-icon">±5</span>} label="Number tile" onClick={()=>add('numberTile')}/><Thing icon={<span className="fraction-icon"><i/><i/><i/><i/></span>} label="Fraction bar" onClick={()=>add('fractionBar')}/><Thing icon={<span className="label-icon">Aa</span>} label="Label" onClick={()=>add('label')}/></div><h3>TABLETOP</h3><div className="thing-grid"><Thing icon={<span className="deck-icon">A♠</span>} label="Card deck" onClick={()=>add('deck')}/><Thing icon={<span className="die-icon">⚄</span>} label="Die" onClick={()=>add('die')}/><Thing icon={<span className="pawn-icon"/>} label="Pawn" onClick={()=>add('pawn')}/></div><div className="color-row">{palette.map(c=><button key={c} style={{background:c}} className={color===c?'active':''} onClick={()=>setColor(c)} aria-label={`Choose ${c}`}/>)}</div></div></aside>
    <div className="room-actions"><div className="reactions"><button onClick={()=>setReactionMenu(!reactionMenu)}>☺</button>{reactionMenu&&<div>{['👍','🎉','💡','👏'].map(e=><button key={e} onClick={()=>{react(e);setReactionMenu(false)}}>{e}</button>)}</div>}</div>{me.isTutor&&<div className="tutor-menu"><button onClick={()=>control(snapshot.locked?'unlock':'lock')}>{snapshot.locked?'🔒 Board locked':'🔓 Lock board'}</button><button onClick={()=>control('reset-view')}>⌗ Reset views</button><button className="danger" onClick={()=>confirm('Clear everything from this board?')&&emit({type:'clear'})}>Clear</button></div>}</div>
    {snapshot.locked&&!me.isTutor&&<div className="locked-banner">🔒 The tutor paused editing. You can still look around.</div>}
  </div>;
}

function Thing({icon,label,onClick}:{icon:React.ReactNode;label:string;onClick:()=>void}){return <button className="thing" onClick={onClick}>{icon}<span>{label}</span><b>+</b></button>}

function ObjectNode({object:o,selected,canEdit,onSelect,onUpdate,onAction}:{object:BoardObject;selected:boolean;canEdit:boolean;onSelect:(e:any)=>void;onUpdate:(p:Partial<BoardObject>)=>void;onAction:(t:any)=>void}){
  const common={id:o.id,x:o.x,y:o.y,rotation:o.rotation,scaleX:o.scaleX,scaleY:o.scaleY,draggable:canEdit&&!o.locked,onClick:onSelect,onTap:onSelect,onDragEnd:(e:any)=>onUpdate({x:e.target.x(),y:e.target.y()}),onTransformEnd:(e:any)=>onUpdate({x:e.target.x(),y:e.target.y(),rotation:e.target.rotation(),scaleX:e.target.scaleX(),scaleY:e.target.scaleY()}),shadowColor:selected?'#3974e8':'#24324a',shadowBlur:selected?10:4,shadowOpacity:selected?.22:.1};
  if(o.type==='stroke')return <Line {...common} points={o.points} stroke={o.color} strokeWidth={o.width} opacity={o.opacity} lineCap="round" lineJoin="round" tension={.25}/>;
  if(o.type==='text')return <Text {...common} text={o.text} fill={o.color} fontSize={o.fontSize} width={o.width} fontFamily="Inter, sans-serif" onDblClick={()=>{const text=prompt('Edit text',o.text);if(text!==null)onUpdate({text} as any)}}/>;
  if(o.type==='shape'){if(o.shapeType==='ellipse')return <Ellipse {...common} radiusX={Math.abs(o.width/2)} radiusY={Math.abs(o.height/2)} offsetX={-o.width/2} offsetY={-o.height/2} fill={o.fill} stroke={o.stroke} strokeWidth={o.strokeWidth}/>;if(o.shapeType==='line')return <Line {...common} points={[0,0,o.width,o.height]} stroke={o.stroke} strokeWidth={o.strokeWidth} lineCap="round"/>;if(o.shapeType==='arrow')return <Arrow {...common} points={[0,0,o.width,o.height]} stroke={o.stroke} fill={o.stroke} strokeWidth={o.strokeWidth} pointerLength={12} pointerWidth={12}/>;return <Rect {...common} width={o.width} height={o.height} fill={o.fill} stroke={o.stroke} strokeWidth={o.strokeWidth} cornerRadius={5}/>;}
  if(o.type==='counter')return <Circle {...common} radius={o.size/2} fill={o.color} stroke="white" strokeWidth={4}/>;
  if(o.type==='numberTile')return <Group {...common}><Rect width={68} height={68} offsetX={34} offsetY={34} cornerRadius={12} fill={o.color}/><Text text={String(o.value)} width={68} height={68} offsetX={34} offsetY={26} align="center" verticalAlign="middle" fill="white" fontSize={27} fontStyle="bold"/></Group>;
  if(o.type==='fractionBar')return <Group {...common}>{Array.from({length:o.parts},(_,i)=><Rect key={i} x={i*o.width/o.parts} width={o.width/o.parts} height={o.height} fill={i<o.shaded?o.color:'white'} stroke="#334155" strokeWidth={1.5}/>)}</Group>;
  if(o.type==='card'){const red=o.suit==='♥'||o.suit==='♦';return <Group {...common} onDblClick={()=>onAction('flipCard')}><Rect width={68} height={94} offsetX={34} offsetY={47} cornerRadius={8} fill={o.faceUp?'white':'#3974e8'} stroke={selected?'#3974e8':'#cbd3df'} strokeWidth={2}/>{o.faceUp?<><Text x={-25} y={-39} text={o.rank} fill={red?'#d8404b':'#202938'} fontSize={19} fontStyle="bold"/><Text x={-25} y={-20} text={o.suit} fill={red?'#d8404b':'#202938'} fontSize={17}/><Text x={-14} y={-17} width={28} height={40} text={o.suit} align="center" verticalAlign="middle" fill={red?'#d8404b':'#202938'} fontSize={29}/></>:<><Rect x={-27} y={-40} width={54} height={80} cornerRadius={5} fill="#3974e8" stroke="white" dash={[3,3]}/><Text x={-18} y={-14} width={36} text="M" align="center" fill="white" fontSize={27} fontStyle="bold"/></>}</Group>}
  if(o.type==='deck')return <Group {...common} onDblClick={()=>onAction('drawCard')}><Rect x={-31} y={-43} width={68} height={94} cornerRadius={8} fill="#d9e5ff" stroke="#9ab5eb"/><Rect x={-35} y={-47} width={68} height={94} cornerRadius={8} fill="#3974e8" stroke="white" dash={[4,3]}/><Text x={-22} y={-13} width={42} text="M" align="center" fill="white" fontSize={31} fontStyle="bold"/><Rect x={-23} y={31} width={44} height={20} cornerRadius={8} fill="#202938"/><Text x={-23} y={35} width={44} text={String(o.cards.length)} align="center" fill="white" fontSize={12}/></Group>;
  if(o.type==='die')return <Group {...common} onDblClick={()=>onAction('rollDie')}><Rect width={70} height={70} offsetX={35} offsetY={35} cornerRadius={15} fill="white" stroke={o.color} strokeWidth={3}/><Text width={70} height={70} offsetX={35} offsetY={27} text={['','⚀','⚁','⚂','⚃','⚄','⚅'][o.value]} align="center" verticalAlign="middle" fill={o.color} fontSize={48}/></Group>;
  return <Group {...common}><Circle y={20} radius={24} fill={o.color}/><Circle y={-22} radius={15} fill={o.color}/><Rect x={-31} y={38} width={62} height={14} cornerRadius={7} fill={o.color}/>{o.label&&<Text x={-18} y={-30} width={36} text={o.label} align="center" fill="white" fontSize={14} fontStyle="bold"/>}</Group>;
}
