import { useEffect, useMemo, useRef, useState } from 'react';
import type Konva from 'konva';
import { Arrow, Circle, Ellipse, Group, Image as KonvaImage, Layer, Line, Rect, Stage, Text, Transformer } from 'react-konva';
import type { BoardCommand, BoardObject, ImageObject, Participant, RoomSnapshot, StrokeObject, Tool } from '../shared/types';

type Viewport={x:number;y:number;scale:number};
type ThingKind='counter'|'numberTile'|'fractionBar'|'label'|'deck'|'die'|'pawn'|'chip';
const palette=['#3974e8','#e85c62','#24a47a','#9a62db','#f1a737'];
const tools:{id:Tool;icon:string;label:string;key?:string}[]=[{id:'select',icon:'↖',label:'Select',key:'V'},{id:'hand',icon:'✋',label:'Pan',key:'H'},{id:'pencil',icon:'✎',label:'Pencil',key:'P'},{id:'highlighter',icon:'▰',label:'Highlighter'},{id:'eraser',icon:'⌫',label:'Eraser',key:'E'},{id:'text',icon:'T',label:'Text',key:'T'},{id:'rectangle',icon:'□',label:'Rectangle',key:'R'},{id:'ellipse',icon:'○',label:'Ellipse',key:'O'},{id:'line',icon:'╱',label:'Line',key:'L'},{id:'arrow',icon:'→',label:'Arrow',key:'A'}];
const uuid=()=>crypto.randomUUID();
const base=(type:BoardObject['type'],x:number,y:number,creator:string,z:number)=>({id:uuid(),type,x,y,rotation:0,scaleX:1,scaleY:1,z,locked:false,creator,revision:0});
const deckCodes=()=>['A','2','3','4','5','6','7','8','9','10','J','Q','K'].flatMap(r=>[0,1,2,3].map(s=>`${r}${s}`));

function objectSize(o:BoardObject){
  if(o.type==='fractionBar'||o.type==='image'||o.type==='shape')return{width:Math.abs(o.width*o.scaleX),height:Math.abs(o.height*o.scaleY)};
  if(o.type==='text')return{width:o.width*o.scaleX,height:o.fontSize*1.5*o.scaleY};
  if(o.type==='card')return{width:72*o.scaleX,height:98*o.scaleY};
  if(o.type==='deck')return{width:72*o.scaleX,height:128*o.scaleY};
  if(o.type==='pawn')return{width:66*o.scaleX,height:78*o.scaleY};
  const size=o.type==='counter'||o.type==='chip'?o.size:72;return{width:size*o.scaleX,height:size*o.scaleY};
}

export function Board({snapshot,me,emit,sendCursor,react,control,onError}:{snapshot:RoomSnapshot;me:Participant;emit:(c:BoardCommand)=>void;sendCursor:(p:{x:number;y:number},s:string[])=>void;react:(e:string)=>void;control:(a:'lock'|'unlock'|'reset-view')=>void;onError:(e:string)=>void}){
  const [tool,setTool]=useState<Tool>('select');const [color,setColor]=useState(palette[0]);const [selected,setSelected]=useState<string[]>([]);const [drawer,setDrawer]=useState(true);const [viewport,setViewport]=useState<Viewport>({x:0,y:0,scale:1});const [draft,setDraft]=useState<BoardObject>();const [isPanning,setPanning]=useState(false);const [reactionMenu,setReactionMenu]=useState(false);const [dragPreview,setDragPreview]=useState<{label:string;x:number;y:number}>();const stageRef=useRef<Konva.Stage>(null);const trRef=useRef<Konva.Transformer>(null);const start=useRef({x:0,y:0});const pinch=useRef<{dist:number;center:{x:number;y:number}}|undefined>(undefined);const deckGesture=useRef<{id:string;start:{x:number;y:number};current:{x:number;y:number};moved:boolean}|undefined>(undefined);const lastStrokeSend=useRef(0);const clipboard=useRef<BoardObject[]>([]);const pendingObjects=useRef<BoardObject[]>([]);
  const canEdit=!snapshot.locked||me.isTutor; const selectedObjects=snapshot.objects.filter(o=>selected.includes(o.id));
  const selectionStyle=useMemo(()=>{if(!selectedObjects.length)return{};const x=selectedObjects.reduce((sum,o)=>sum+o.x,0)/selectedObjects.length,y=Math.min(...selectedObjects.map(o=>o.y-objectSize(o).height/2));const screenX=viewport.x+x*viewport.scale,screenY=viewport.y+y*viewport.scale;const left=Math.max(180,Math.min(innerWidth-(drawer?330:100),screenX));const above=screenY-58;return{left,top:Math.max(8,Math.min(innerHeight-128,above<8?screenY+72:above))};},[selectedObjects,viewport,drawer]);
  useEffect(()=>{const nodes=selected.map(id=>stageRef.current?.findOne(`#${id}`)).filter(Boolean) as Konva.Node[];trRef.current?.nodes(nodes);trRef.current?.getLayer()?.batchDraw();},[selected,snapshot.objects]);
  useEffect(()=>{const received=new Set(snapshot.objects.map(o=>o.id));pendingObjects.current=pendingObjects.current.filter(o=>!received.has(o.id));},[snapshot.objects]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches('input,textarea'))return;const mod=e.ctrlKey||e.metaKey;const match=!mod&&tools.find(t=>t.key?.toLowerCase()===e.key.toLowerCase());if(match)setTool(match.id);if((e.key==='Delete'||e.key==='Backspace')&&selected.length)emit({type:'delete',ids:selected});if(mod&&e.key==='z')emit({type:e.shiftKey?'redo':'undo'});if(mod&&e.key==='d'){e.preventDefault();duplicate();}if(mod&&e.key==='c'){e.preventDefault();clipboard.current=structuredClone(selectedObjects);}if(mod&&e.key==='v'&&clipboard.current.length){e.preventDefault();clipboard.current.forEach(o=>createObject({...structuredClone(o),id:uuid(),x:o.x+28,y:o.y+28,creator:me.id,revision:0,z:snapshot.objects.length}));}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
  useEffect(()=>{const reset=()=>fitContent(); window.addEventListener('manipad-reset-view',reset);return()=>window.removeEventListener('manipad-reset-view',reset);},[snapshot.objects]);
  useEffect(()=>{const paste=(event:ClipboardEvent)=>{if(event.target instanceof HTMLElement&&event.target.matches('input,textarea'))return;const item=[...(event.clipboardData?.items||[])].find(entry=>entry.type.startsWith('image/'));const file=item?.getAsFile();if(!file)return;event.preventDefault();void pasteImage(file);};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste);});
  const point=()=>{const p=stageRef.current?.getPointerPosition()||{x:0,y:0};return{x:(p.x-viewport.x)/viewport.scale,y:(p.y-viewport.y)/viewport.scale};};
  function imagePoint(p:{x:number;y:number},image:ImageObject){const angle=-image.rotation*Math.PI/180,dx=p.x-image.x,dy=p.y-image.y;return{x:(dx*Math.cos(angle)-dy*Math.sin(angle))/image.scaleX,y:(dx*Math.sin(angle)+dy*Math.cos(angle))/image.scaleY};}
  function eventObject(e:any){let node=e.target,stage=e.target.getStage();while(node&&node!==stage){const id=node.id?.();const object=id&&snapshot.objects.find(item=>item.id===id);if(object)return object;node=node.getParent?.();}return undefined;}
  function createObject(object:BoardObject){if(!canEdit){onError('The tutor locked the board');return;}if(!snapshot.objects.some(o=>o.id===object.id)&&!pendingObjects.current.some(o=>o.id===object.id))pendingObjects.current.push(object);emit({type:'create',object});}
  function center(){return{x:(innerWidth/2-viewport.x)/viewport.scale,y:((innerHeight-64)/2-viewport.y)/viewport.scale};}
  function worldAtClient(clientX:number,clientY:number){return{x:(clientX-viewport.x)/viewport.scale,y:(clientY-64-viewport.y)/viewport.scale};}
  function availablePosition(desired:{x:number;y:number},width:number,height:number){const occupied=[...snapshot.objects,...pendingObjects.current];for(let step=0;step<24;step++){const ring=Math.ceil(step/4),angle=(step%4)*Math.PI/2+(ring%2)*Math.PI/4;const candidate=step===0?desired:{x:desired.x+Math.cos(angle)*ring*44,y:desired.y+Math.sin(angle)*ring*44};const blocked=occupied.some(o=>{const size=objectSize(o);return Math.abs(o.x-candidate.x)<(size.width+width)/2*.72&&Math.abs(o.y-candidate.y)<(size.height+height)/2*.72;});if(!blocked)return candidate;}return{x:desired.x+48,y:desired.y+48};}
  function buildThing(kind:ThingKind,position:{x:number;y:number}){const z=snapshot.objects.length,b=base(kind==='label'?'text':kind,position.x,position.y,me.id,z);if(kind==='counter')return{...b,type:'counter' as const,color,size:54};if(kind==='numberTile')return{...b,type:'numberTile' as const,value:5,color};if(kind==='fractionBar')return{...b,type:'fractionBar' as const,parts:4,shaded:3,color,width:220,height:52};if(kind==='deck'){const cards=deckCodes();return{...b,type:'deck' as const,cards,initialCards:[...cards],faceUp:false};}if(kind==='die')return{...b,type:'die' as const,value:4,color,rollNonce:0};if(kind==='pawn')return{...b,type:'pawn' as const,color,label:'A'};if(kind==='chip')return{...b,type:'chip' as const,side:'front' as const,frontText:'1',backText:'A',frontColor:color,backColor:palette[(palette.indexOf(color)+1)%palette.length],size:64};return{...b,type:'text' as const,text:'Double-tap to edit',color:'#202938',fontSize:24,width:220};}
  function add(kind:ThingKind,desired=center(),avoidOverlap=true){const probe=buildThing(kind,desired),size=objectSize(probe),position=avoidOverlap?availablePosition(desired,size.width,size.height):desired;createObject(buildThing(kind,position));}
  function dropThing(kind:ThingKind,clientX:number,clientY:number){const drawerWidth=innerWidth<=800?240:280;if(clientY<64||clientX<0||clientX>innerWidth||(drawer&&clientX>innerWidth-drawerWidth))return;add(kind,worldAtClient(clientX,clientY),false);}
  async function pasteImage(file:File){if(!canEdit){onError('The tutor locked the board');return;}if(file.size>8_000_000){onError('That image is too large to paste');return;}const source=URL.createObjectURL(file);try{const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const el=new Image();el.onload=()=>resolve(el);el.onerror=reject;el.src=source;});const max=1000,scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),width=Math.max(80,Math.round(image.naturalWidth*scale)),height=Math.max(80,Math.round(image.naturalHeight*scale));const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;canvas.getContext('2d')!.drawImage(image,0,0,width,height);const src=canvas.toDataURL('image/png');const position=availablePosition(center(),width,height);createObject({...base('image',position.x,position.y,me.id,snapshot.objects.length),type:'image',src,width,height,alt:file.name||'Pasted image'});}catch{onError('Could not paste that image');}finally{URL.revokeObjectURL(source);}}
  function down(e:any){if(e.evt.touches?.length===2){const[a,b]=e.evt.touches;pinch.current={dist:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),center:{x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2}};return;}const p=point();start.current=p;if((tool==='pencil'||tool==='highlighter')&&canEdit){const image=eventObject(e);const parentImage=image?.type==='image'?image:undefined,first=parentImage?imagePoint(p,parentImage):p;const stroke={...base('stroke',0,0,me.id,snapshot.objects.length),type:'stroke' as const,points:[first.x,first.y],color:tool==='highlighter'?'#f6cf45':color,width:tool==='highlighter'?18:4,opacity:tool==='highlighter' ? .32 : 1,...(parentImage?{parentImageId:parentImage.id}:{})};setDraft(stroke);createObject(stroke);return;}if(e.target!==e.target.getStage())return;if(tool==='select'){setSelected([]);return;}if(tool==='hand'){setPanning(true);return;}if(!canEdit)return;if(tool==='text'){const text=prompt('Add text');if(text)createObject({...base('text',p.x,p.y,me.id,snapshot.objects.length),type:'text',text,color:'#202938',fontSize:26,width:260});return;}if(['rectangle','ellipse','line','arrow'].includes(tool)){setDraft({...base('shape',p.x,p.y,me.id,snapshot.objects.length),type:'shape',shapeType:tool as any,width:1,height:1,fill:tool==='rectangle'||tool==='ellipse'?'#ffffff':'transparent',stroke:color,strokeWidth:3});}}
  function move(e:any){if(e.evt.touches?.length===2&&pinch.current){e.evt.preventDefault();const[a,b]=e.evt.touches;const dist=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),centerNow={x:(a.clientX+b.clientX)/2,y:(a.clientY+b.clientY)/2};const old=viewport.scale,newScale=Math.max(.2,Math.min(3,old*(dist/pinch.current.dist)));const world={x:(pinch.current.center.x-viewport.x)/old,y:(pinch.current.center.y-viewport.y)/old};setViewport({scale:newScale,x:centerNow.x-world.x*newScale,y:centerNow.y-world.y*newScale});pinch.current={dist,center:centerNow};return;}const p=point();sendCursor(p,selected);if(deckGesture.current){deckGesture.current.current=p;deckGesture.current.moved=deckGesture.current.moved||Math.hypot(p.x-deckGesture.current.start.x,p.y-deckGesture.current.start.y)>8;}if(isPanning){setViewport(v=>({...v,x:v.x+(e.evt.movementX||0),y:v.y+(e.evt.movementY||0)}));return;}if(!draft)return;if(draft.type==='stroke'){const image=draft.parentImageId?snapshot.objects.find((object):object is ImageObject=>object.id===draft.parentImageId&&object.type==='image'):undefined,pixel=image?imagePoint(p,image):p;const next={...draft,points:[...draft.points,pixel.x,pixel.y]};setDraft(next);if(Date.now()-lastStrokeSend.current>40){emit({type:'update',ids:[draft.id],patch:{points:next.points} as Partial<BoardObject>});lastStrokeSend.current=Date.now();}}else if(draft.type==='shape')setDraft({...draft,width:p.x-start.current.x,height:p.y-start.current.y});}
  function up(){pinch.current=undefined;setPanning(false);if(deckGesture.current){const gesture=deckGesture.current;deckGesture.current=undefined;emit({type:'drawCard',id:gesture.id,...(gesture.moved?{position:gesture.current}:{})});}if(draft){if(draft.type==='stroke')emit({type:'update',ids:[draft.id],patch:{points:draft.points} as Partial<BoardObject>});else createObject(draft);setDraft(undefined);}}
  function wheel(e:any){e.evt.preventDefault();const stage=stageRef.current,p=stage?.getPointerPosition();if(!p)return;const old=viewport.scale,scaleBy=1.08,next=e.evt.deltaY>0?old/scaleBy:old*scaleBy,newScale=Math.max(.2,Math.min(3,next));const world={x:(p.x-viewport.x)/old,y:(p.y-viewport.y)/old};setViewport({scale:newScale,x:p.x-world.x*newScale,y:p.y-world.y*newScale});}
  function fitContent(){if(!snapshot.objects.length){setViewport({x:0,y:0,scale:1});return;}const xs=snapshot.objects.map(o=>o.x),ys=snapshot.objects.map(o=>o.y);const minX=Math.min(...xs)-120,maxX=Math.max(...xs)+220,minY=Math.min(...ys)-120,maxY=Math.max(...ys)+180;const s=Math.min(1,(innerWidth-220)/(maxX-minX),(innerHeight-180)/(maxY-minY));setViewport({scale:s,x:(innerWidth-(minX+maxX)*s)/2,y:(innerHeight-(minY+maxY)*s)/2});}
  function duplicate(){selectedObjects.forEach(o=>createObject({...structuredClone(o),id:uuid(),x:o.x+24,y:o.y+24,creator:me.id,revision:0,z:snapshot.objects.length}));}
  function selectObject(id:string,e:any){if(tool==='eraser'){emit({type:'delete',ids:[id]});return;}if(tool!=='select')return;setSelected(s=>e.evt.shiftKey?(s.includes(id)?s.filter(x=>x!==id):[...s,id]):[id]);}
  function updateObject(o:BoardObject,patch:Partial<BoardObject>){
    if((o.type==='card'||o.type==='deck')&&typeof patch.x==='number'&&typeof patch.y==='number'){
      const target=snapshot.objects.filter(item=>item.id!==o.id&&(item.type==='card'||item.type==='deck')&&Math.hypot(item.x-patch.x!,item.y-patch.y!)<52).sort((a,b)=>b.z-a.z)[0];
      if(target){emit({type:'mergeIntoDeck',sourceId:o.id,targetId:target.id});setSelected([]);return;}
    }
    emit({type:'update',ids:[o.id],patch});
  }
  function editChip(chip:Extract<BoardObject,{type:'chip'}>){const frontText=prompt('Front text',chip.frontText);if(frontText===null)return;const backText=prompt('Back text',chip.backText);if(backText===null)return;const frontColor=prompt('Front color (hex)',chip.frontColor);if(frontColor===null)return;const backColor=prompt('Back color (hex)',chip.backColor);if(backColor===null)return;const hex=/^#[0-9a-f]{6}$/i;emit({type:'update',ids:[chip.id],patch:{frontText:frontText.slice(0,12),backText:backText.slice(0,12),frontColor:hex.test(frontColor)?frontColor:chip.frontColor,backColor:hex.test(backColor)?backColor:chip.backColor} as Partial<BoardObject>});}
  function imageAnnotations(id:string):StrokeObject[]{const strokes=snapshot.objects.filter((object):object is StrokeObject=>object.type==='stroke'&&object.parentImageId===id);if(draft?.type==='stroke'&&draft.parentImageId===id&&!snapshot.objects.some(item=>item.id===draft.id))return[...strokes,draft];return strokes;}
  const backgroundStrokes=snapshot.objects.filter((o)=>o.type==='stroke'&&!o.parentImageId).sort((a,b)=>a.z-b.z),foreground=snapshot.objects.filter((o)=>o.type!=='stroke').sort((a,b)=>a.z-b.z);
  return <div className={`board ${isPanning?'panning':''}`} onDragOver={e=>{if(e.dataTransfer.types.includes('application/x-manipad-thing')||e.dataTransfer.types.includes('text/plain')){e.preventDefault();e.dataTransfer.dropEffect='copy';}}} onDrop={e=>{const raw=e.dataTransfer.getData('application/x-manipad-thing')||e.dataTransfer.getData('text/plain');const kinds:ThingKind[]=['counter','numberTile','fractionBar','label','deck','die','pawn','chip'];if(kinds.includes(raw as ThingKind)){e.preventDefault();dropThing(raw as ThingKind,e.clientX,e.clientY);}}}>
    <div className="tool-rail" role="toolbar" aria-label="Board tools">{tools.map(t=><button key={t.id} className={tool===t.id?'active':''} onClick={()=>setTool(t.id)} title={`${t.label}${t.key?` (${t.key})`:''}`} aria-label={t.label}><span>{t.icon}</span></button>)}<hr/><label className="color-button" title="Tool color" style={{background:color}}><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label></div>
    <Stage ref={stageRef} width={innerWidth} height={innerHeight-64} x={viewport.x} y={viewport.y} scaleX={viewport.scale} scaleY={viewport.scale} onMouseDown={down} onTouchStart={down} onMouseMove={move} onTouchMove={move} onMouseUp={up} onTouchEnd={up} onWheel={wheel}>
      <Layer>{backgroundStrokes.map(o=><ObjectNode key={o.id} object={o} selected={selected.includes(o.id)} canEdit={canEdit} tool={tool} annotations={[]} onDeckStart={()=>{}} onSelect={e=>selectObject(o.id,e)} onUpdate={patch=>updateObject(o,patch)} onAction={type=>emit({type,id:o.id} as BoardCommand)}/>)}{draft?.type==='stroke'&&!draft.parentImageId&&!snapshot.objects.some(o=>o.id===draft.id)&&<ObjectNode object={draft} selected={false} canEdit={false} tool={tool} annotations={[]} onDeckStart={()=>{}} onSelect={()=>{}} onUpdate={()=>{}} onAction={()=>{}}/>}{foreground.map(o=><ObjectNode key={o.id} object={o} selected={selected.includes(o.id)} canEdit={canEdit} tool={tool} annotations={o.type==='image'?imageAnnotations(o.id):[]} onDeckStart={(id,p)=>{deckGesture.current={id,start:p,current:p,moved:false};}} onSelect={e=>selectObject(o.id,e)} onUpdate={patch=>updateObject(o,patch)} onAction={type=>emit({type,id:o.id} as BoardCommand)}/>)}{draft&&draft.type!=='stroke'&&!snapshot.objects.some(o=>o.id===draft.id)&&<ObjectNode object={draft} selected={false} canEdit={false} tool={tool} annotations={[]} onDeckStart={()=>{}} onSelect={()=>{}} onUpdate={()=>{}} onAction={()=>{}}/>}<Transformer ref={trRef} rotateEnabled enabledAnchors={selectedObjects.some(o=>o.type==='stroke')?[]:['top-left','top-right','bottom-left','bottom-right']} boundBoxFunc={(oldBox,newBox)=>Math.abs(newBox.width)<16||Math.abs(newBox.height)<16?oldBox:newBox}/>{snapshot.participants.filter(p=>p.id!==me.id&&p.cursor).map(p=><Group key={p.id} x={p.cursor!.x} y={p.cursor!.y} listening={false}><Line points={[0,0,0,18,5,13,10,22,14,20,9,11,17,11]} closed fill={p.color} stroke="white" strokeWidth={2}/><Rect x={14} y={20} width={Math.max(46,p.name.length*8+14)} height={24} cornerRadius={7} fill={p.color}/><Text x={21} y={26} text={p.name} fill="white" fontSize={12} fontStyle="bold"/></Group>)}</Layer>
    </Stage>
    <div className="history-controls"><button onClick={()=>emit({type:'undo'})} title="Undo">↶</button><button onClick={()=>emit({type:'redo'})} title="Redo">↷</button></div>
    <div className="zoom-controls"><button onClick={()=>setViewport(v=>({...v,scale:Math.max(.2,v.scale-.1)}))}>−</button><span>{Math.round(viewport.scale*100)}%</span><button onClick={()=>setViewport(v=>({...v,scale:Math.min(3,v.scale+.1)}))}>+</button><button onClick={fitContent} title="Fit content">⌗</button></div>
    <div className="minimap"><div className="mini-grid">{snapshot.objects.slice(0,40).map(o=><i key={o.id} data-x={o.x} data-y={o.y} data-type={o.type} data-count={o.type==='deck'?o.cards.length:''} data-parent-image={o.type==='stroke'?o.parentImageId||'':''} style={{left:`${50+Math.max(-45,Math.min(45,o.x/30))}%`,top:`${50+Math.max(-40,Math.min(40,o.y/20))}%`}}/>)}</div></div>
    {selected.length>0&&<div className="selection-bar" style={selectionStyle}><span>{selected.length} selected</span><button onClick={duplicate}>Duplicate</button><button onClick={()=>emit({type:'reorder',ids:selected,direction:'front'})}>To front</button>{selectedObjects.length===1&&selectedObjects[0].type==='card'&&<button onClick={()=>emit({type:'flipCard',id:selected[0]})}>Flip</button>}{selectedObjects.length===1&&selectedObjects[0].type==='chip'&&<><button onClick={()=>emit({type:'flipChip',id:selected[0]})}>Flip</button><button onClick={()=>editChip(selectedObjects[0] as Extract<BoardObject,{type:'chip'}>)}>Edit sides</button></>}{selectedObjects.length===1&&selectedObjects[0].type==='die'&&<button onClick={()=>emit({type:'rollDie',id:selected[0]})}>Roll</button>}{selectedObjects.length===1&&selectedObjects[0].type==='deck'&&<><button onClick={()=>emit({type:'drawCard',id:selected[0]})}>Draw</button><button onClick={()=>emit({type:'drawAndFlip',id:selected[0]})}>Draw &amp; flip</button><button onClick={()=>emit({type:'flipDeck',id:selected[0]})}>Flip</button><button onClick={()=>emit({type:'shuffleDeck',id:selected[0]})}>Shuffle</button><button onClick={()=>emit({type:'resetDeck',id:selected[0]})}>Reset</button></>}<button className="danger" onClick={()=>{emit({type:'delete',ids:selected});setSelected([])}}>Delete</button></div>}
    <aside className={`library ${drawer?'open':''}`}><button className="library-tab" onClick={()=>setDrawer(!drawer)}><span>✦</span><b>Things</b><i>{drawer?'›':'‹'}</i></button><div className="library-body"><h2>Things to move</h2><p>Tap to center, or drag one anywhere.</p><h3>MATH</h3><div className="thing-grid"><Thing kind="counter" icon={<span className="counter-icon"/>} label="Counter" onClick={()=>add('counter')} onDrop={dropThing} onPreview={setDragPreview}/><Thing kind="numberTile" icon={<span className="tile-icon">±5</span>} label="Number tile" onClick={()=>add('numberTile')} onDrop={dropThing} onPreview={setDragPreview}/><Thing kind="fractionBar" icon={<span className="fraction-icon"><i/><i/><i/><i/></span>} label="Fraction bar" onClick={()=>add('fractionBar')} onDrop={dropThing} onPreview={setDragPreview}/><Thing kind="label" icon={<span className="label-icon">Aa</span>} label="Label" onClick={()=>add('label')} onDrop={dropThing} onPreview={setDragPreview}/></div><h3>TABLETOP</h3><div className="thing-grid"><Thing kind="deck" icon={<span className="deck-icon">A♠</span>} label="Card deck" onClick={()=>add('deck')} onDrop={dropThing} onPreview={setDragPreview}/><Thing kind="die" icon={<span className="die-icon">⚄</span>} label="Die" onClick={()=>add('die')} onDrop={dropThing} onPreview={setDragPreview}/><Thing kind="pawn" icon={<span className="pawn-icon"/>} label="Pawn" onClick={()=>add('pawn')} onDrop={dropThing} onPreview={setDragPreview}/><Thing kind="chip" icon={<span className="chip-icon">1</span>} label="Two-sided chip" onClick={()=>add('chip')} onDrop={dropThing} onPreview={setDragPreview}/></div><div className="color-row">{palette.map(c=><button key={c} style={{background:c}} className={color===c?'active':''} onClick={()=>setColor(c)} aria-label={`Choose ${c}`}/>)}</div></div></aside>
    <div className="room-actions"><div className="reactions"><button onClick={()=>setReactionMenu(!reactionMenu)}>☺</button>{reactionMenu&&<div>{['👍','🎉','💡','👏'].map(e=><button key={e} onClick={()=>{react(e);setReactionMenu(false)}}>{e}</button>)}</div>}</div>{me.isTutor&&<div className="tutor-menu"><button onClick={()=>control(snapshot.locked?'unlock':'lock')}>{snapshot.locked?'🔒 Board locked':'🔓 Lock board'}</button><button onClick={()=>control('reset-view')}>⌗ Reset views</button><button className="danger" onClick={()=>confirm('Clear everything from this board?')&&emit({type:'clear'})}>Clear</button></div>}</div>
    {snapshot.locked&&!me.isTutor&&<div className="locked-banner">🔒 The tutor paused editing. You can still look around.</div>}
    {dragPreview&&<div className="thing-drag-preview" style={{left:dragPreview.x,top:dragPreview.y}}>{dragPreview.label}<b>+</b></div>}
  </div>;
}

function Thing({kind,icon,label,onClick,onDrop,onPreview}:{kind:ThingKind;icon:React.ReactNode;label:string;onClick:()=>void;onDrop:(kind:ThingKind,x:number,y:number)=>void;onPreview:(value:{label:string;x:number;y:number}|undefined)=>void}){
  const gesture=useRef<{x:number;y:number;moved:boolean}|undefined>(undefined);const suppress=useRef(false);
  return <button className="thing" draggable
    onDragStart={e=>{e.dataTransfer.setData('application/x-manipad-thing',kind);e.dataTransfer.setData('text/plain',kind);e.dataTransfer.effectAllowed='copy';}}
    onPointerDown={e=>{if(e.pointerType==='mouse')return;gesture.current={x:e.clientX,y:e.clientY,moved:false};e.currentTarget.setPointerCapture(e.pointerId);}}
    onPointerMove={e=>{const g=gesture.current;if(!g)return;if(!g.moved&&Math.hypot(e.clientX-g.x,e.clientY-g.y)>8)g.moved=true;if(g.moved)onPreview({label,x:e.clientX,y:e.clientY-64});}}
    onPointerUp={e=>{const g=gesture.current;gesture.current=undefined;onPreview(undefined);if(g?.moved){suppress.current=true;onDrop(kind,e.clientX,e.clientY);setTimeout(()=>{suppress.current=false;},0);}}}
    onPointerCancel={()=>{gesture.current=undefined;onPreview(undefined);}}
    onClick={e=>{if(suppress.current){e.preventDefault();return;}onClick();}}>{icon}<span>{label}</span><b>+</b></button>;
}

function ObjectNode({object:o,selected,canEdit,tool,annotations,onDeckStart,onSelect,onUpdate,onAction}:{object:BoardObject;selected:boolean;canEdit:boolean;tool:Tool;annotations:StrokeObject[];onDeckStart:(id:string,p:{x:number;y:number})=>void;onSelect:(e:any)=>void;onUpdate:(p:Partial<BoardObject>)=>void;onAction:(t:any)=>void}){
  const common={id:o.id,x:o.x,y:o.y,rotation:o.rotation,scaleX:o.scaleX,scaleY:o.scaleY,draggable:canEdit&&!o.locked&&tool==='select',onClick:onSelect,onTap:onSelect,onDragEnd:(e:any)=>onUpdate({x:e.target.x(),y:e.target.y()}),onTransformEnd:(e:any)=>onUpdate({x:e.target.x(),y:e.target.y(),rotation:e.target.rotation(),scaleX:e.target.scaleX(),scaleY:e.target.scaleY()}),shadowColor:selected?'#3974e8':'#24324a',shadowBlur:selected?10:4,shadowOpacity:selected?.22:.1};
  if(o.type==='stroke')return <Line {...common} points={o.points} stroke={o.color} strokeWidth={o.width} opacity={o.opacity} lineCap="round" lineJoin="round" tension={.25}/>;
  if(o.type==='text'){const edit=()=>{const text=prompt('Edit text',o.text);if(text!==null)onUpdate({text} as any)};return <Text {...common} text={o.text} fill={o.color} fontSize={o.fontSize} width={o.width} fontFamily="Inter, sans-serif" onDblClick={edit} onDblTap={edit}/>;}
  if(o.type==='shape'){if(o.shapeType==='ellipse')return <Ellipse {...common} radiusX={Math.abs(o.width/2)} radiusY={Math.abs(o.height/2)} offsetX={-o.width/2} offsetY={-o.height/2} fill={o.fill} stroke={o.stroke} strokeWidth={o.strokeWidth}/>;if(o.shapeType==='line')return <Line {...common} points={[0,0,o.width,o.height]} stroke={o.stroke} strokeWidth={o.strokeWidth} lineCap="round"/>;if(o.shapeType==='arrow')return <Arrow {...common} points={[0,0,o.width,o.height]} stroke={o.stroke} fill={o.stroke} strokeWidth={o.strokeWidth} pointerLength={12} pointerWidth={12}/>;return <Rect {...common} width={o.width} height={o.height} fill={o.fill} stroke={o.stroke} strokeWidth={o.strokeWidth} cornerRadius={5}/>;}
  if(o.type==='counter')return <Circle {...common} radius={o.size/2} fill={o.color} stroke="white" strokeWidth={4}/>;
  if(o.type==='numberTile')return <Group {...common}><Rect width={68} height={68} offsetX={34} offsetY={34} cornerRadius={12} fill={o.color}/><Text text={String(o.value)} width={68} height={68} offsetX={34} offsetY={26} align="center" verticalAlign="middle" fill="white" fontSize={27} fontStyle="bold"/></Group>;
  if(o.type==='fractionBar')return <Group {...common}>{Array.from({length:o.parts},(_,i)=><Rect key={i} x={i*o.width/o.parts} width={o.width/o.parts} height={o.height} fill={i<o.shaded?o.color:'white'} stroke="#334155" strokeWidth={1.5}/>)}</Group>;
  if(o.type==='card'){const red=o.suit==='♥'||o.suit==='♦',flip=(e:any)=>{if(tool==='select'&&canEdit){onAction('flipCard');onSelect(e);}};return <Group {...common} onClick={flip} onTap={flip}><Rect width={68} height={94} offsetX={34} offsetY={47} cornerRadius={8} fill={o.faceUp?'white':'#3974e8'} stroke={selected?'#3974e8':'#cbd3df'} strokeWidth={2}/>{o.faceUp?<><Text x={-25} y={-39} text={o.rank} fill={red?'#d8404b':'#202938'} fontSize={19} fontStyle="bold"/><Text x={-25} y={-20} text={o.suit} fill={red?'#d8404b':'#202938'} fontSize={17}/><Text x={-14} y={-17} width={28} height={40} text={o.suit} align="center" verticalAlign="middle" fill={red?'#d8404b':'#202938'} fontSize={29}/></>:<><Rect x={-27} y={-40} width={54} height={80} cornerRadius={5} fill="#3974e8" stroke="white" dash={[3,3]}/><Text x={-18} y={-14} width={36} text="M" align="center" fill="white" fontSize={27} fontStyle="bold"/></>}</Group>}
  if(o.type==='deck'){const startDeck=(e:any)=>{if(tool==='select'&&canEdit){const stage=e.target.getStage(),pointer=stage?.getPointerPosition();if(pointer)onDeckStart(o.id,{x:(pointer.x-stage.x())/stage.scaleX(),y:(pointer.y-stage.y())/stage.scaleY()});}},code=o.cards.at(-1)||'A0',suits=['♠','♥','♦','♣'] as const,suit=suits[Number(code.slice(-1))]||'♠',rank=code.slice(0,-1),red=suit==='♥'||suit==='♦',deckCommon={...common,draggable:false,onClick:undefined,onTap:undefined};return <Group {...deckCommon}><Group onMouseDown={startDeck} onTouchStart={startDeck}><Rect x={-31} y={-43} width={68} height={94} cornerRadius={8} fill="#d9e5ff" stroke="#9ab5eb"/><Rect x={-35} y={-47} width={68} height={94} cornerRadius={8} fill={o.faceUp?'white':'#3974e8'} stroke={o.faceUp?'#cbd3df':'white'} dash={o.faceUp?undefined:[4,3]}/>{o.faceUp?<><Text x={-25} y={-39} text={rank} fill={red?'#d8404b':'#202938'} fontSize={19} fontStyle="bold"/><Text x={-25} y={-20} text={suit} fill={red?'#d8404b':'#202938'} fontSize={17}/><Text x={-14} y={-17} width={28} height={40} text={suit} align="center" verticalAlign="middle" fill={red?'#d8404b':'#202938'} fontSize={29}/></>:<Text x={-22} y={-13} width={42} text="M" align="center" fill="white" fontSize={31} fontStyle="bold"/>}</Group><Group x={0} y={62} draggable={canEdit&&!o.locked&&tool==='select'} onClick={onSelect} onTap={onSelect} onDragEnd={(e:any)=>{const node=e.target;onUpdate({x:o.x+node.x(),y:o.y+node.y()-62});node.position({x:0,y:62});}}><Rect x={-25} y={-11} width={50} height={24} cornerRadius={10} fill="#202938" stroke="white" strokeWidth={2}/><Text x={-25} y={-5} width={50} text={String(o.cards.length)} align="center" fill="white" fontSize={12} fontStyle="bold"/></Group></Group>}
  if(o.type==='die'){const roll=()=>onAction('rollDie');return <Group {...common} onDblClick={roll} onDblTap={roll}><Rect width={70} height={70} offsetX={35} offsetY={35} cornerRadius={15} fill="white" stroke={o.color} strokeWidth={3}/><Text width={70} height={70} offsetX={35} offsetY={27} text={['','⚀','⚁','⚂','⚃','⚄','⚅'][o.value]} align="center" verticalAlign="middle" fill={o.color} fontSize={48}/></Group>}
  if(o.type==='chip'){const flip=()=>onAction('flipChip'),front=o.side==='front',chipColor=front?o.frontColor:o.backColor,chipText=front?o.frontText:o.backText;return <Group {...common} onDblClick={flip} onDblTap={flip}><Circle radius={o.size/2} fill={chipColor} stroke="white" strokeWidth={4}/><Circle radius={o.size/2-7} stroke="white" strokeWidth={1.5} dash={[3,3]} opacity={.75}/><Text width={o.size} height={o.size} offsetX={o.size/2} offsetY={o.size/2-2} text={chipText} align="center" verticalAlign="middle" fill="white" fontSize={Math.min(24,Math.max(12,34-chipText.length*2))} fontStyle="bold"/></Group>}
  if(o.type==='image')return <Group {...common}><ImageNode object={o}/><Group clipX={-o.width/2} clipY={-o.height/2} clipWidth={o.width} clipHeight={o.height} listening={false}>{annotations.map(stroke=><Line key={stroke.id} points={stroke.points} stroke={stroke.color} strokeWidth={stroke.width} opacity={stroke.opacity} lineCap="round" lineJoin="round" tension={.25}/>)}</Group></Group>;
  return <Group {...common}><Circle y={20} radius={24} fill={o.color}/><Circle y={-22} radius={15} fill={o.color}/><Rect x={-31} y={38} width={62} height={14} cornerRadius={7} fill={o.color}/>{o.label&&<Text x={-18} y={-30} width={36} text={o.label} align="center" fill="white" fontSize={14} fontStyle="bold"/>}</Group>;
}

function ImageNode({object}:{object:ImageObject}){const [image,setImage]=useState<HTMLImageElement|undefined>(undefined);useEffect(()=>{const next=new Image();next.onload=()=>setImage(next);next.src=object.src;return()=>{next.onload=null;};},[object.src]);return <KonvaImage image={image} width={object.width} height={object.height} offsetX={object.width/2} offsetY={object.height/2}/>;}
